name: Docker WinTenCermin

on:
  push:
    paths:
      - "Dockerfile-WinTenCermin-megasdkrest"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-WinTenCermin-megasdkrest
          platforms: linux/amd64
          push: true
          tags: jovanzers/wintencermin-megasdkrest:latest

      - name: Alert via Telegram
        run: |
          function sendTG() {
              curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" \
              --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown&disable_notification=True"
          }
          sendTG "*Docker WinTenCermin-megasdkrest container has been updated:* [Link](https://hub.docker.com/r/jovanzers/wintencermin-megasdkrest/tags)" &> /dev/null
